/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
	T extends ColumnType<infer S, infer I, infer U>
		? ColumnType<S, I | undefined, U>
		: ColumnType<T, T | undefined, T>;

export interface Group {
	displayName: string;
	id: string;
	prefix: string;
}

export interface Homework {
	closed: boolean;
	id: Generated<number>;
	issue: number;
	studentId: number;
	title: string;
}

export interface Student {
	github: string;
	groupId: string;
	id: Generated<number>;
	telegram: string;
}

export interface DB {
	group: Group;
	homework: Homework;
	student: Student;
}
